Python_projects/Website_scraping/project_poetry/hw10_project/hw10_project/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as views_users
from quotes import views as views_quotes
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("quotes.urls")),
    path('signup/', views_users.signupuser, name='signup'),
    path('users/', include('users.urls')),
    #path('login/', views.login, name='login'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('profile/', views_users.profile, name='profile'),
    path('add/', views_quotes.add_quote, name='add_quote'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Python_projects/Website_scraping/project_poetry/hw10_project/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root_paginate"),
    path('add/', views.add_quote, name='add_quote'),
    path('author/create/', views.author_create, name='author_create'),
    path('author/<str:fullname>/', views.author_detail, name='author_detail'),
]

Python_projects/Website_scraping/project_poetry/hw10_project/users/urls.py
from django.urls import path
from . import views


app_name = 'users'


urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
]

Python_projects/Website_scraping/project_poetry/hw10_project/quotes/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

Python_projects/Website_scraping/project_poetry/hw10_project/quotes/forms.py
from django import forms

from .models import Quote, Author

class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['quote', 'author', 'tags']

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

Python_projects/Website_scraping/project_poetry/hw10_project/quotes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from .forms import QuoteForm, AuthorForm
from .models import Author, Quote

# Create your views here.

def main(request, page=1):
    quotes = Quote.objects.select_related('author').prefetch_related('tags').all()
    per_page = 10
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.page(page)

    return render(request, "quotes/index.html", context={"quotes": quotes_on_page, "paginator":paginator})

@login_required()
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            quote = form.save(commit=False)
            quote.user = request.user
            quote.save()
            form.save_m2m()
            return redirect('quotes:root')
    else:
        form = QuoteForm()
    return render(request, 'quotes/add_quote.html', {'form': form})

def author_detail(request, fullname):
    author = get_object_or_404(Author, fullname=fullname)
    return render(request, 'quotes/author_detail.html', {'author': author})

@login_required()
def author_create(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quotes:add_quote')
    else:
        form = AuthorForm()
    return render(request, 'quotes/author_create.html', {'form': form})

Python_projects/Website_scraping/project_poetry/hw10_project/quotes/templates/quotes/add_quote.html
{% extends 'quotes/base.html' %}

{% block content %}

<h1 style="text-decoration: none">Add Quote</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% if form.errors %}
<div>
    <ul>
        {% for field in form %}
        {% for error in field.errors %}
        <li><strong>{{ field.label }}:</strong> {{ error }}</li>
        {% endfor %}
        {% endfor %}
    </ul>
</div>
{% endif %}

{% endblock %}

Python_projects/Website_scraping/project_poetry/hw10_project/quotes/templates/quotes/author_create.html
{% extends 'quotes/base.html' %}

{% block content %}

<h1>Create New Author</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

{% endblock %}

Python_projects/Website_scraping/project_poetry/hw10_project/quotes/templates/quotes/author_detail.html
{% extends 'quotes/base.html' %}

{% block content %}

<div class="author-details">
    <h3 class="author-title">{{ author.fullname }}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{ author.born_date }}</span> <span
            class="author-born-location">{{ author.born_location }}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{ author.description }}
    </div>
</div>

{% endblock %}

Python_projects/Website_scraping/project_poetry/hw10_project/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Homework</title>
</head>

<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                {% if user.is_authenticated %}
                <p>
                    {% if user.profile %}
                    <a href="{% url 'users:profile' %}" class="btn btn-outline-primary">{{ user.username }}</a>
                    {% else %}
                    <a href="{% url 'users:profile' %}" class="btn btn-primary">Profile</a>
                    {% endif %}
                    <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
                </p>
                {% else %}
                <p>
                    You are not logged in. <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a> or <a
                        href="{% url 'users:signup' %}" class="btn btn-primary">Sign Up</a>
                </p>
                {% endif %}
                {% if user.is_authenticated %}
                <p>
                    <a href="{% url 'add_quote' %}" class="btn btn-outline-secondary">+ Add quote</a>
                    <a href="{% url 'quotes:author_create' %}" class="btn btn-outline-secondary">+ Add author</a>
                </p>
                {% endif %}
            </div>
        </div>


        {% block content %} {% endblock %}



    </div>
</body>

</html>

Python_projects/Website_scraping/project_poetry/hw10_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}

{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}

        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
                <a href="/author/{{quote.author}}">(about)</a>
            </span>
            <div class="tags">
                Tags:

                {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
                {% endfor %}

            </div>
        </div>
        {% endfor %}
        <nav>
            <ul class="pagination justify-content-center">
                {% if quotes.has_previous %}
                <li class="page-item">
                    <a class="page-link"
                       href="{% url 'quotes:root_paginate' quotes.previous_page_number %}">Previous</a>
                </li>
                {% endif %}
        
                {% for page_num in paginator.page_range %}
                <li class="page-item {% if page_num == quotes.number %}active{% endif %}">
                    <a class="page-link" href="{% url 'quotes:root_paginate' page_num %}">{{ page_num }}</a>
                </li>
                {% endfor %}
        
                {% if quotes.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'quotes:root_paginate' quotes.next_page_number %}">Next</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>

{% endblock %}